/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class ConsumerAppTest {
    @Test public void appHasAGreeting() {
        ConsumerApp classUnderTest = new ConsumerApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
